### ISSUE TITLE
Dividing a fraction by another fraction fails

### ISSUE THREAD

**Issue by jwg4** [bradley101/fraction#3]
Hi, using Python 3.6. Dividing one fraction by another should produce a result, instead it's 
```
TypeError: unsupported operand type(s) for /: 'Fraction' and 'Fraction'
```

**Comment by bradley101** [comment]
Hi @jwg4 
As python 2.x does not support the __div__ operator function. It is causing the error.
We will release the fix today. 
Thanks for the support ♥

**Comment by bradley101** [comment]
Please upgrade the fraction module to the latest version
`pip install fraction --upgrade`

**Comment by jwg4** [comment]
Thanks very much for resolving this, it works.
