### ISSUE TITLE
str and repr should show a canonical representation

### ISSUE THREAD

**Issue by jwg4** [bradley101/fraction#4]
Hi!
It would be nice if str() and repr() showed a canonical representation of the fraction. For example 
```
>>> x = Fraction(6, 4)
>>> x
Fraction(3, 2)
```
That way it would be clear in tests and examples exactly what the value is.

**Comment by bradley101** [comment]
Thanks. you can create your branch and raise a pull request to master branch including your fix.

**Comment by bradley101** [comment]
PR merged 👍
