### ISSUE TITLE
Fraction doesn't handle  0x2044 divider

### ISSUE THREAD

**Issue by weightwatchers-carlanderson** [bradley101/fraction#7]
Fraction doesn't handle the division symbol (a⁄b) i.e. 0x2044. 

<pre>
>>> from fractions import Fraction
>>> Fraction("1/2")
Fraction(1, 2)
>>> Fraction("1⁄2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/fractions.py", line 138, in __new__
    numerator)
ValueError: Invalid literal for Fraction: '1⁄2'
</pre>

github is causing problems me showing the issue well as it tries to autocorrect it but it is clearer in this screenshot

![Screen Shot 2021-03-15 at 6 35 20 PM](https://user-images.githubusercontent.com/39501603/111230199-992b5880-85bd-11eb-8c04-0266ccc861c1.png)

**Comment by bradley101** [comment]
Initializing the object with a string literal is not supported. You need to initialize by specifying numerator and denominator.
```
>>> a = Fraction(1, 2)
>>> print(a)
1/2
```
So are you expecting `Fraction(1, 2)` will result in 0.5 ?

**Comment by weightwatchers-carlanderson** [comment]
@bradley101 

>So are you expecting Fraction(1, 2) will result in 0.5 ?

no, the opposite; that `Fraction("1/2")` is recognized as a valid fraction and does not throw a valueerror

Typically initializing with a string does in fact work:

```
>>> from fractions import Fraction
>>> Fraction("3/4")
Fraction(3, 4)
>>> Fraction("5/8")
Fraction(5, 8)
>>> Fraction("0/4")
Fraction(0, 1)

>>> Fraction("x/4")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/fractions.py", line 138, in __new__
    numerator)
ValueError: Invalid literal for Fraction: 'x/4'
```
Thus, I was suggesting that it should work with other division characters. I did not realize that this was not an actual feature

**Comment by weightwatchers-carlanderson** [comment]
Ok, the issue is actually in /opt/anaconda3/lib/python3.7/fractions.py  in the _RATIONAL_FORMAT regex

**Comment by bradley101** [comment]
In fact I'm getting the error
```
>>> Fraction("5/8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\shantanu.banerjee\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\fraction\Fraction.py", line 3, in __init__
    self.numerator = int(numerator)
ValueError: invalid literal for int() with base 10: '5/8'
```

You should avoid using and initializing the constructor with a string literal. Meanwhile you can create a fix and open a PR.
Closing this 👍
