### ISSUE TITLE
Fraction to Decimal and vice versa

### ISSUE THREAD

**Issue by Tommimon** [bradley101/fraction#8]
I would like to use this package to perform calculation with fractions and then get the result as decimal.

This will avoid problems like `0.7*0.7 = 0.48999999999999994`.

My idea is to add two new methods `toDecimal()` and `fromDecimal()` for the job.

I have a pretty good idea of how to implement this feature but before starting working I want to know if you think is a good idea and if there is any chance this get merged.

**Comment by bradley101** [comment]
Apology for seeing this issue late. Nice issue. Will be working on it in the upcoming version. Expect it to be done within 2-3 days.

**Comment by bradley101** [comment]
The release is getting delayed due to a lot of testing and testcases being written. This is going to be a big change and release.  Except it to be done ASAP.

**Comment by bradley101** [comment]
Please upgrade to the latest version
```
python3 -m pip install Fraction --upgrade
```
Go through the documentation on how to use the new features.
